### ISSUE TITLE
onDidReceiveBackgroundNotificationResponse

### ISSUE THREAD

**Issue by himsa** [rithik-dev/firebase_notifications_handler#10] opened 2024-09-26 11:05 UTC
is there any plan to implement onDidReceiveBackgroundNotificationResponse?
or is it already handled by handleInitialMessage ?

**Comment by rithik-dev** [comment] 2024-09-28 09:27
Hey @himsa, I checked that function but could not get that to trigger in any test scenario. I am not sure when that is called, but I will check that and update the usage if needed.

However, everything related to notifications like on taps, initial messages etc. work fine in all the states of the app i.e. foreground, background or terminated.

Closing this issue as the package does work as intended.

**Comment by himsa** [comment] 2024-09-30 04:01
I that will trigger when app is fully cleared from system
so I handle it like this
@pragma('vm:entry-point')
void notificationTapBackground(NotificationResponse notificationResponse) {
  StorageMethods.find.setData(
    StorageNames.fcmData,
    jsonDecode(notificationResponse.payload!),
  );
}

so I save the data first because the app is not minimized but fully cleared
then I check that data when app open to do the routing or something else

I just tried it in firebase_notifications_handler, I think the on tap is not triggered, it is triggered when app is in minimize, but not if fully cleared

sorry for the late reply, please check again, thank you

**Comment by rithik-dev** [comment] 2024-09-30 06:58
Hey @himsa, thank you for the insights. I'll check this and let you know about my observations.

**Comment by rithik-dev** [comment] 2024-10-06 18:51
Hey @himsa, I tested this scenario and in my testing, the onTap callback in the widget did trigger, and works as expected.

Let me know if you have a specific test scenario which causes the widget to not trigger the onTap callback and I'll check further.

Closing this for now.

**Closed as completed by rithik-dev** 2024-10-06 18:51 UTC
